#!/data/data/com.termux/files/usr/bin/bash


# pkg install apt
# pkg install bash
# pkg install binutils-is-llvm
# pkg install brotli
# pkg install bzip2
# pkg install ca-certificates
# pkg install clang
# pkg install cmake
# pkg install command-not-found
# pkg install coreutils
# pkg install curl
# pkg install dash
# pkg install debianutils
# pkg install dialog
# pkg install diffutils
# pkg install dos2unix
# pkg install dpkg
# pkg install ed
# pkg install findutils
# pkg install fontconfig
# pkg install freetype
# pkg install gawk
# pkg install gdbm
# pkg install ghostscript
# pkg install git-crypt
# pkg install git
# pkg install glib
# pkg install gpgv
# pkg install grep
# pkg install gzip
# pkg install htop
# pkg install inetutils
# pkg install jbig2dec
# pkg install jsoncpp
# pkg install krb5
# pkg install ldns
# pkg install less
# pkg install libandroid-execinfo
# pkg install libandroid-glob
# pkg install libandroid-posix-semaphore
# pkg install libandroid-selinux
# pkg install libandroid-support
# pkg install libarchive
# pkg install libassuan
# pkg install libbz2
# pkg install libc++
# pkg install libcap-ng
# pkg install libcompiler-rt
# pkg install libcrypt
# pkg install libcurl
# pkg install libdb
# pkg install libedit
# pkg install libevent
# pkg install libexpat
# pkg install libffi
# pkg install libgcrypt
# pkg install libgmp
# pkg install libgnutls
# pkg install libgpg-error
# pkg install libiconv
# pkg install libicu
# pkg install libidn2
# pkg install libidn
# pkg install libjpeg-turbo
# pkg install libllvm
# pkg install liblz4
# pkg install liblzma
# pkg install libmd
# pkg install libmpfr
# pkg install libnettle
# pkg install libnghttp2
# pkg install libnghttp3
# pkg install libnpth
# pkg install libpng
# pkg install libresolv-wrapper
# pkg install libsmartcols
# pkg install libsqlite
# pkg install libssh2
# pkg install libtiff
# pkg install libtirpc
# pkg install libunbound
# pkg install libunistring
# pkg install libuv
# pkg install libxml2
# pkg install littlecms
# pkg install lld
# pkg install llvm
# pkg install lsof
# pkg install make
# pkg install nano
# pkg install ncurses-ui-libs
# pkg install ncurses
# pkg install ndk-sysroot
# pkg install net-tools
# pkg install openjpeg
# pkg install openssh-sftp-server
# pkg install openssh
# pkg install openssl-tool
# pkg install openssl
# pkg install patch
# pkg install pcre2
# pkg install pkg-config
# pkg install procps
# pkg install psmisc
# pkg install python-ensurepip-wheels
# pkg install python-pip
# pkg install python
# pkg install rclone
# pkg install readline
# pkg install resolv-conf
# pkg install rhash
# pkg install ruff
# pkg install rust-std-aarch64-linux-android
# pkg install rust
# pkg install sed
# pkg install sqlite
# pkg install tar
# pkg install termux-am-socket
# pkg install termux-am
# pkg install termux-auth
# pkg install termux-core
# pkg install termux-exec
# pkg install termux-keyring
# pkg install termux-licenses
# pkg install termux-tools
# pkg install ttf-dejavu
# pkg install unzip
# pkg install util-linux
# pkg install xxhash
# pkg install xz-utils
# pkg install zlib
# pkg install zstd
# pip install ------------------
# pip install aiohappyeyeballs
# pip install aiohttp
# pip install aiohttp-jinja2
# pip install aiosignal
# pip install asttokens
# pip install attrs
# pip install Camelot
# pip install certifi
# pip install cffi
# pip install chardet
# pip install charset-normalizer
# pip install cheap_repr
# pip install click
# pip install cryptography
# pip install decorator
# pip install Elixir
# pip install executing
# pip install frozenlist
# pip install idna
# pip install isort
# pip install Jinja2
# pip install linkify-it-py
# pip install logica
# pip install markdown-it-py
# pip install MarkupSafe
# pip install maturin
# pip install mdit-py-plugins
# pip install mdurl
# pip install msgpack
# pip install multidict
# pip install pbr
# pip install pip
# pip install platformdirs
# pip install propcache
# pip install pycparser
# pip install Pygments
# pip install requests
# pip install rich
# pip install setuptools
# pip install six
# pip install snoop
# pip install SQLAlchemy
# pip install sqlalchemy-migrate
# pip install sqlparse
# pip install tarjan
# pip install Tempita
# pip install textual
# pip install textual-dev
# pip install textual-serve
# pip install textualize
# pip install typing_extensions
# pip install uc-micro-py
# pip install urllib3
# pip install veryfi
# pip install xlrd
# pip install xlwt
# pip install xxhash
# pip install yarl
